### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by shyusu4** [shyusu4/space-travelers-hub#25]
Hi! 😄 This is an issue for information about our team and Kanban board.

**There are 2 people in our team:**
Student A - @shyusu4
Student B - @X-Elie-X 

**This is the link to our kanban board:**
https://github.com/shyusu4/space-travelers-hub/projects/1

**Comment by dasileker** [comment]
### **Hi @X-Elie-X,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
